name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  scan-leaks:
    name: Deteccion de Secretos (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ejecutar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  scan-sast:
    name: Analisis de Codigo (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4
      - name: Ejecutar Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

  scan-sca:
    name: Analisis de Dependencias (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4
      - name: Ejecutar Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'library'